//! Upload state machine and resource store.
//!
//! Implements the full upload protocol from RFC 0011 §3 and
//! resource-store/spec.md lines 46-124:
//!
//! ## Fast path (inline, ≤ 64 KiB)
//!
//! A `ResourceUploadStart` with `inline_data` populated is processed in a
//! single call to `handle_upload_start`.  No chunk messages are needed.
//!
//! ## Chunked path (> 64 KiB)
//!
//! 1. `handle_upload_start` — register the upload, perform dedup check.
//! 2. `handle_upload_chunk` — accumulate chunks in order.
//! 3. `handle_upload_complete` — validate hash, decode, store.
//!
//! ## Deduplication
//!
//! On `handle_upload_start`, the runtime checks `expected_hash` against the
//! dedup index.  If found, `ResourceStored { was_deduplicated: true }` is
//! returned immediately and no chunk sequence follows.
//!
//! ## Concurrency limits
//!
//! Each agent may have at most `MAX_CONCURRENT_UPLOADS_PER_AGENT` (= 4)
//! uploads in flight simultaneously.

use std::collections::HashMap;
use std::sync::Arc;
use std::time::Instant;

use tokio::sync::Mutex;

use crate::dedup::{DedupIndex, ResourceRecord};
use crate::types::{
    ResourceError, ResourceId, ResourceStoreConfig, ResourceStored, ResourceType,
    CHUNK_SIZE_LIMIT, INLINE_SIZE_LIMIT, MAX_CONCURRENT_UPLOADS_PER_AGENT,
};
use crate::validation::{
    AgentBudget, check_budget, check_capability, check_hash, check_raw_size, check_resource_type,
    decode_and_validate,
};

// ─── Upload session ───────────────────────────────────────────────────────────

/// Opaque upload ID generated by the client (UUIDv7 encoded as bytes, or any
/// 16-byte sequence).  Scoped per agent.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct UploadId([u8; 16]);

impl UploadId {
    pub fn from_bytes(b: [u8; 16]) -> Self {
        Self(b)
    }

    pub fn from_slice(s: &[u8]) -> Option<Self> {
        let arr: [u8; 16] = s.try_into().ok()?;
        Some(Self(arr))
    }
}

/// State of a single in-flight chunked upload.
struct InflightUpload {
    #[allow(dead_code)] // retained for diagnostics/tracing
    upload_id: UploadId,
    resource_type: ResourceType,
    /// BLAKE3 hash the agent declared in `ResourceUploadStart.expected_hash`.
    expected_hash: [u8; 32],
    /// Total expected byte count declared in `ResourceUploadStart.total_size`.
    total_size: usize,
    /// Accumulated chunks in arrival order; validated for monotonic chunk index.
    chunks: Vec<Vec<u8>>,
    /// Index of the next expected chunk (0-based).
    next_chunk_index: u32,
    /// Wall-clock time of upload start (for rate limiting accounting).
    #[allow(dead_code)]
    started_at: Instant,
}

impl InflightUpload {
    fn accumulated_bytes(&self) -> usize {
        self.chunks.iter().map(|c| c.len()).sum()
    }

    fn assemble(&self) -> Vec<u8> {
        let total = self.accumulated_bytes();
        let mut buf = Vec::with_capacity(total);
        for chunk in &self.chunks {
            buf.extend_from_slice(chunk);
        }
        buf
    }
}

// ─── Per-agent upload registry ────────────────────────────────────────────────

/// Tracks in-flight uploads for a single agent.
struct AgentUploads {
    inflight: HashMap<UploadId, InflightUpload>,
}

impl AgentUploads {
    fn new() -> Self {
        Self {
            inflight: HashMap::new(),
        }
    }

    fn count(&self) -> usize {
        self.inflight.len()
    }
}

// ─── ResourceStore ────────────────────────────────────────────────────────────

/// The resource store — thread-safe, `Clone`-able via inner `Arc`.
///
/// ## Usage
///
/// ```ignore
/// use tze_hud_resource::{ResourceStore, ResourceStoreConfig};
///
/// let store = ResourceStore::new(ResourceStoreConfig::default());
/// // ... handle_upload_start, handle_upload_chunk, handle_upload_complete
/// ```
#[derive(Clone)]
pub struct ResourceStore {
    dedup: DedupIndex,
    config: Arc<ResourceStoreConfig>,
    /// Per-agent upload state.  Keyed by agent namespace string.
    agent_uploads: Arc<Mutex<HashMap<String, AgentUploads>>>,
}

impl ResourceStore {
    /// Create a new empty resource store.
    pub fn new(config: ResourceStoreConfig) -> Self {
        Self {
            dedup: DedupIndex::new(),
            config: Arc::new(config),
            agent_uploads: Arc::new(Mutex::new(HashMap::new())),
        }
    }

    /// Reference to the underlying dedup index (for scene-graph refcount ops).
    pub fn dedup_index(&self) -> &DedupIndex {
        &self.dedup
    }

    // ─── Handle upload start ─────────────────────────────────────────────────

    /// Process a `ResourceUploadStart` message.
    ///
    /// # Fast path (inline data)
    ///
    /// If `req.inline_data` is non-empty (and ≤ 64 KiB), the upload is
    /// completed immediately in this call.  Returns `Ok(Some(result))`.
    ///
    /// # Dedup fast path
    ///
    /// If `req.expected_hash` matches a known resource, returns
    /// `Ok(Some(ResourceStored { was_deduplicated: true }))` immediately.
    /// No chunks needed.
    ///
    /// # Chunked path
    ///
    /// Returns `Ok(None)` — the caller should collect chunks and call
    /// `handle_upload_complete`.
    ///
    /// # Errors
    ///
    /// - `CapabilityDenied` — agent lacks `upload_resource` capability.
    /// - `TooManyUploads` — agent already has 4 uploads in flight.
    /// - `SizeExceeded` — inline data > 64 KiB or > `max_resource_bytes`.
    /// - `UnsupportedType` — `resource_type` not in the v1 set.
    /// - `HashMismatch` — inline data hash does not match `expected_hash`.
    /// - `DecodeError` — inline data fails decode validation.
    /// - `BudgetExceeded` — decoded size would exceed agent or runtime limit.
    pub async fn handle_upload_start(
        &self,
        req: UploadStartRequest,
    ) -> Result<Option<ResourceStored>, ResourceError> {
        // 1. Capability gate.
        check_capability(&req.agent_capabilities)?;

        // 5. Type check (cheap; do early to short-circuit).
        check_resource_type(req.resource_type)?;

        // Dedup fast path: check expected_hash against known resources.
        // Latency contract: < 100 µs (spec lines 112-113).
        if self.dedup.contains(&ResourceId::from_bytes(req.expected_hash)) {
            let resource_id = ResourceId::from_bytes(req.expected_hash);
            let record = self.dedup.get(&resource_id).expect("just confirmed present");
            tracing::debug!(
                resource_id = %resource_id,
                agent = %req.agent_namespace,
                "dedup hit — skipping upload"
            );
            return Ok(Some(ResourceStored {
                resource_id,
                was_deduplicated: true,
                decoded_bytes: record.decoded_bytes,
            }));
        }

        // ── Inline fast path ───────────────────────────────────────────────
        if !req.inline_data.is_empty() {
            if req.inline_data.len() > INLINE_SIZE_LIMIT {
                return Err(ResourceError::SizeExceeded {
                    detail: format!(
                        "inline_data {} bytes exceeds 64 KiB inline limit",
                        req.inline_data.len()
                    ),
                });
            }
            return self
                .complete_upload(
                    req.inline_data,
                    req.expected_hash,
                    req.resource_type,
                    &req.agent_capabilities,
                    &req.agent_budget,
                    &req.agent_namespace,
                )
                .await
                .map(Some);
        }

        // ── Chunked path: register in-flight upload ────────────────────────
        check_raw_size(req.total_size, &self.config)?;

        let upload_id = req.upload_id;
        let mut guard = self.agent_uploads.lock().await;
        let entry = guard
            .entry(req.agent_namespace.clone())
            .or_insert_with(AgentUploads::new);

        if entry.count() >= MAX_CONCURRENT_UPLOADS_PER_AGENT {
            return Err(ResourceError::TooManyUploads);
        }

        if entry.inflight.contains_key(&upload_id) {
            return Err(ResourceError::InvalidChunk(format!(
                "upload_id {:?} already in flight for agent {}",
                upload_id, req.agent_namespace
            )));
        }

        entry.inflight.insert(
            upload_id,
            InflightUpload {
                upload_id,
                resource_type: req.resource_type,
                expected_hash: req.expected_hash,
                total_size: req.total_size,
                chunks: Vec::new(),
                next_chunk_index: 0,
                started_at: Instant::now(),
            },
        );

        tracing::debug!(
            agent = %req.agent_namespace,
            upload_id = ?upload_id,
            total_size = req.total_size,
            "chunked upload registered"
        );

        Ok(None)
    }

    // ─── Handle upload chunk ─────────────────────────────────────────────────

    /// Process a `ResourceUploadChunk` message.
    ///
    /// Chunks MUST arrive in sequential 0-based order.  Out-of-order chunks
    /// are rejected with `InvalidChunk`.
    ///
    /// Individual chunk sizes are limited to `CHUNK_SIZE_LIMIT` (64 KiB).
    pub async fn handle_upload_chunk(
        &self,
        agent_namespace: &str,
        upload_id: UploadId,
        chunk_index: u32,
        data: Vec<u8>,
    ) -> Result<(), ResourceError> {
        if data.len() > CHUNK_SIZE_LIMIT {
            return Err(ResourceError::InvalidChunk(format!(
                "chunk size {} exceeds 64 KiB limit",
                data.len()
            )));
        }

        let mut guard = self.agent_uploads.lock().await;
        let uploads = guard
            .get_mut(agent_namespace)
            .ok_or_else(|| ResourceError::InvalidChunk("no uploads in flight for agent".into()))?;

        let inflight = uploads
            .inflight
            .get_mut(&upload_id)
            .ok_or_else(|| ResourceError::InvalidChunk(format!(
                "unknown upload_id {:?}", upload_id
            )))?;

        if chunk_index != inflight.next_chunk_index {
            return Err(ResourceError::InvalidChunk(format!(
                "expected chunk index {} but got {}",
                inflight.next_chunk_index, chunk_index
            )));
        }

        // Guard against exceeding declared total size.
        let accumulated = inflight.accumulated_bytes() + data.len();
        if accumulated > inflight.total_size {
            return Err(ResourceError::SizeExceeded {
                detail: format!(
                    "accumulated chunk bytes {} exceed declared total_size {}",
                    accumulated, inflight.total_size
                ),
            });
        }

        inflight.chunks.push(data);
        inflight.next_chunk_index += 1;

        Ok(())
    }

    // ─── Handle upload complete ───────────────────────────────────────────────

    /// Process a `ResourceUploadComplete` message.
    ///
    /// Assembles all chunks, runs full validation (hash, size, type, decode,
    /// budget), and stores the resource.
    ///
    /// # Errors
    ///
    /// Same error set as `handle_upload_start` plus `InvalidChunk` if the
    /// `upload_id` is not known.
    pub async fn handle_upload_complete(
        &self,
        agent_namespace: &str,
        upload_id: UploadId,
        agent_capabilities: &[String],
        agent_budget: &AgentBudget,
    ) -> Result<ResourceStored, ResourceError> {
        // Extract the inflight state.
        let (resource_type, expected_hash, assembled) = {
            let mut guard = self.agent_uploads.lock().await;
            let uploads = guard
                .get_mut(agent_namespace)
                .ok_or_else(|| ResourceError::InvalidChunk(
                    "no uploads in flight for agent".into(),
                ))?;

            let inflight = uploads
                .inflight
                .remove(&upload_id)
                .ok_or_else(|| ResourceError::InvalidChunk(format!(
                    "unknown upload_id {:?}", upload_id
                )))?;

            let assembled = inflight.assemble();
            (inflight.resource_type, inflight.expected_hash, assembled)
        };

        self.complete_upload(
            assembled,
            expected_hash,
            resource_type,
            agent_capabilities,
            agent_budget,
            agent_namespace,
        )
        .await
    }

    // ─── Abort an upload ─────────────────────────────────────────────────────

    /// Abort and discard an in-flight upload.
    ///
    /// Called when the session disconnects mid-upload or the agent sends an
    /// explicit abort.
    pub async fn abort_upload(&self, agent_namespace: &str, upload_id: UploadId) {
        let mut guard = self.agent_uploads.lock().await;
        if let Some(uploads) = guard.get_mut(agent_namespace) {
            uploads.inflight.remove(&upload_id);
        }
    }

    /// Abort all in-flight uploads for an agent (on session disconnect).
    pub async fn abort_all_uploads(&self, agent_namespace: &str) {
        let mut guard = self.agent_uploads.lock().await;
        guard.remove(agent_namespace);
    }

    /// Current number of in-flight uploads for an agent.
    pub async fn in_flight_count(&self, agent_namespace: &str) -> usize {
        let guard = self.agent_uploads.lock().await;
        guard
            .get(agent_namespace)
            .map(|u| u.count())
            .unwrap_or(0)
    }

    // ─── Internal: complete upload and store ──────────────────────────────────

    async fn complete_upload(
        &self,
        data: Vec<u8>,
        expected_hash: [u8; 32],
        resource_type: ResourceType,
        agent_capabilities: &[String],
        agent_budget: &AgentBudget,
        agent_namespace: &str,
    ) -> Result<ResourceStored, ResourceError> {
        // Check capability (may already be checked but re-check for inline/complete paths).
        check_capability(agent_capabilities)?;

        // Raw size check.
        check_raw_size(data.len(), &self.config)?;

        // Type check.
        check_resource_type(resource_type)?;

        // BLAKE3 hash integrity.
        check_hash(&data, &expected_hash)?;

        // Decode validation (also checks decoded size limits).
        let meta = decode_and_validate(&data, resource_type, &self.config)?;

        // Budget check.
        let runtime_used = self.dedup.total_decoded_bytes();
        check_budget(meta.decoded_bytes, agent_budget, runtime_used, &self.config)?;

        // Max concurrent resources check.
        if self.dedup.len() >= self.config.max_concurrent_resources {
            return Err(ResourceError::BudgetExceeded {
                detail: format!(
                    "max concurrent resources {} reached",
                    self.config.max_concurrent_resources
                ),
            });
        }

        // Insert into dedup index.
        let resource_id = ResourceId::from_bytes(expected_hash);
        let record = ResourceRecord::new(resource_id, resource_type, &meta);

        let (resource_id, was_deduplicated) = match self.dedup.insert(resource_id, record) {
            Ok(rec) => {
                tracing::info!(
                    resource_id = %rec.resource_id,
                    agent = %agent_namespace,
                    decoded_bytes = meta.decoded_bytes,
                    "resource stored"
                );
                (rec.resource_id, false)
            }
            Err(existing) => {
                // Race: another upload completed between our dedup check and
                // insert.  Return the existing record (still correct content).
                tracing::debug!(
                    resource_id = %existing.resource_id,
                    agent = %agent_namespace,
                    "dedup race — returning existing record"
                );
                (existing.resource_id, true)
            }
        };

        Ok(ResourceStored {
            resource_id,
            was_deduplicated,
            decoded_bytes: meta.decoded_bytes,
        })
    }
}

// ─── Request types ────────────────────────────────────────────────────────────

/// Parameters for `handle_upload_start`, corresponding to a `ResourceUploadStart`
/// protocol message.
pub struct UploadStartRequest {
    /// Agent namespace string (for per-agent concurrency tracking).
    pub agent_namespace: String,
    /// Capabilities held by the agent.
    pub agent_capabilities: Vec<String>,
    /// Agent's current budget state.
    pub agent_budget: AgentBudget,
    /// Opaque upload ID (client-generated, scoped per agent).
    pub upload_id: UploadId,
    /// Resource type.
    pub resource_type: ResourceType,
    /// Expected BLAKE3 hash of the complete content.
    pub expected_hash: [u8; 32],
    /// Total declared byte count (used for pre-flight size check on chunked path).
    /// May be 0 if not declared; size is still checked after assembly.
    pub total_size: usize,
    /// Inline data for the fast path (empty for chunked).
    pub inline_data: Vec<u8>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::validation::test_helpers::minimal_png_1x1;

    fn default_store() -> ResourceStore {
        ResourceStore::new(ResourceStoreConfig::default())
    }

    fn caps() -> Vec<String> {
        vec!["upload_resource".to_string()]
    }

    fn unlimited_budget() -> AgentBudget {
        AgentBudget {
            texture_bytes_total_limit: 0,
            texture_bytes_total_used: 0,
        }
    }

    fn upload_id(n: u8) -> UploadId {
        UploadId::from_bytes([n; 16])
    }

    use crate::validation::AgentBudget;
    use crate::types::ResourceStoreConfig;

    // ─── Inline fast path ─────────────────────────────────────────────────────

    #[tokio::test]
    async fn inline_png_upload_succeeds() {
        let store = default_store();
        let data = minimal_png_1x1();
        let hash = *blake3::hash(&data).as_bytes();

        let result = store
            .handle_upload_start(UploadStartRequest {
                agent_namespace: "agent-a".into(),
                agent_capabilities: caps(),
                agent_budget: unlimited_budget(),
                upload_id: upload_id(1),
                resource_type: ResourceType::ImagePng,
                expected_hash: hash,
                total_size: data.len(),
                inline_data: data.clone(),
            })
            .await
            .unwrap()
            .unwrap();

        assert!(!result.was_deduplicated);
        assert_eq!(result.resource_id.as_bytes(), &hash);
        assert_eq!(result.decoded_bytes, 4); // 1×1 RGBA8
    }

    // Acceptance: inline upload for small resource (spec lines 78-79).
    #[tokio::test]
    async fn inline_upload_requires_no_chunks_or_complete() {
        let store = default_store();
        let data = minimal_png_1x1();
        let hash = *blake3::hash(&data).as_bytes();

        let result = store
            .handle_upload_start(UploadStartRequest {
                agent_namespace: "agent-b".into(),
                agent_capabilities: caps(),
                agent_budget: unlimited_budget(),
                upload_id: upload_id(2),
                resource_type: ResourceType::ImagePng,
                expected_hash: hash,
                total_size: data.len(),
                inline_data: data,
            })
            .await
            .unwrap();

        // Returns Some immediately — no chunk/complete messages needed.
        assert!(result.is_some());
    }

    // ─── Dedup fast path ──────────────────────────────────────────────────────

    // Acceptance: dedup hit returns existing with was_deduplicated=true (spec lines 108-109).
    #[tokio::test]
    async fn dedup_hit_returns_immediately() {
        let store = default_store();
        let data = minimal_png_1x1();
        let hash = *blake3::hash(&data).as_bytes();

        // First upload stores the resource.
        let first = store
            .handle_upload_start(UploadStartRequest {
                agent_namespace: "agent-a".into(),
                agent_capabilities: caps(),
                agent_budget: unlimited_budget(),
                upload_id: upload_id(1),
                resource_type: ResourceType::ImagePng,
                expected_hash: hash,
                total_size: data.len(),
                inline_data: data.clone(),
            })
            .await
            .unwrap()
            .unwrap();

        assert!(!first.was_deduplicated);

        // Second upload (different agent, same content) hits dedup.
        let second = store
            .handle_upload_start(UploadStartRequest {
                agent_namespace: "agent-b".into(),
                agent_capabilities: caps(),
                agent_budget: unlimited_budget(),
                upload_id: upload_id(2),
                resource_type: ResourceType::ImagePng,
                expected_hash: hash,
                total_size: data.len(),
                inline_data: data.clone(),
            })
            .await
            .unwrap()
            .unwrap();

        assert!(second.was_deduplicated);
        assert_eq!(first.resource_id, second.resource_id);
    }

    // Acceptance: identical bytes produce identical ResourceId (spec lines 11-12).
    #[tokio::test]
    async fn identical_bytes_same_resource_id() {
        let store = default_store();
        let data = minimal_png_1x1();
        let hash = *blake3::hash(&data).as_bytes();

        let req = || UploadStartRequest {
            agent_namespace: "agent-x".into(),
            agent_capabilities: caps(),
            agent_budget: unlimited_budget(),
            upload_id: upload_id(1),
            resource_type: ResourceType::ImagePng,
            expected_hash: hash,
            total_size: data.len(),
            inline_data: data.clone(),
        };

        let r1 = store.handle_upload_start(req()).await.unwrap().unwrap();
        let r2 = store.handle_upload_start(req()).await.unwrap().unwrap();

        assert_eq!(r1.resource_id, r2.resource_id);
    }

    // ─── Chunked upload ───────────────────────────────────────────────────────

    // Acceptance: chunked upload 3-phase success (spec lines 62-64).
    #[tokio::test]
    async fn chunked_upload_success() {
        let store = default_store();
        let agent = "chunked-agent";
        let uid = upload_id(10);

        // Build 200 KiB of data (> 64 KiB inline limit).
        let chunk_size = 64 * 1024;
        let total_size = chunk_size * 4; // 4 × 64 KiB
        let raw_data: Vec<u8> = (0..total_size).map(|i| (i % 251) as u8).collect();
        let hash = *blake3::hash(&raw_data).as_bytes();

        // Start.
        let start_result = store
            .handle_upload_start(UploadStartRequest {
                agent_namespace: agent.into(),
                agent_capabilities: caps(),
                agent_budget: unlimited_budget(),
                upload_id: uid,
                resource_type: ResourceType::ImageRgba8,
                expected_hash: hash,
                total_size,
                inline_data: vec![],
            })
            .await
            .unwrap();

        // Chunked path returns None.
        assert!(start_result.is_none());

        // Send 4 chunks.
        for i in 0u32..4 {
            let offset = (i as usize) * chunk_size;
            let chunk = raw_data[offset..offset + chunk_size].to_vec();
            store
                .handle_upload_chunk(agent, uid, i, chunk)
                .await
                .unwrap();
        }

        // Complete.
        let result = store
            .handle_upload_complete(agent, uid, &caps(), &unlimited_budget())
            .await
            .unwrap();

        assert!(!result.was_deduplicated);
        assert_eq!(result.resource_id.as_bytes(), &hash);
    }

    // Acceptance: hash mismatch rejected (spec lines 66-68).
    #[tokio::test]
    async fn chunked_upload_hash_mismatch() {
        let store = default_store();
        let agent = "hash-mismatch-agent";
        let uid = upload_id(20);

        let chunk_size = 64 * 1024;
        let total_size = chunk_size * 2;
        let raw_data: Vec<u8> = vec![0xab; total_size];
        let wrong_hash = [0u8; 32]; // intentionally wrong

        store
            .handle_upload_start(UploadStartRequest {
                agent_namespace: agent.into(),
                agent_capabilities: caps(),
                agent_budget: unlimited_budget(),
                upload_id: uid,
                resource_type: ResourceType::ImageRgba8,
                expected_hash: wrong_hash,
                total_size,
                inline_data: vec![],
            })
            .await
            .unwrap();

        for i in 0u32..2 {
            let offset = (i as usize) * chunk_size;
            let chunk = raw_data[offset..offset + chunk_size].to_vec();
            store
                .handle_upload_chunk(agent, uid, i, chunk)
                .await
                .unwrap();
        }

        let err = store
            .handle_upload_complete(agent, uid, &caps(), &unlimited_budget())
            .await
            .unwrap_err();

        assert!(matches!(err, ResourceError::HashMismatch { .. }));
        assert_eq!(err.wire_code(), "RESOURCE_HASH_MISMATCH");
    }

    // ─── Capability check ─────────────────────────────────────────────────────

    // Acceptance: guest agent rejected (spec lines 88-90).
    #[tokio::test]
    async fn upload_denied_without_capability() {
        let store = default_store();
        let data = minimal_png_1x1();
        let hash = *blake3::hash(&data).as_bytes();

        let err = store
            .handle_upload_start(UploadStartRequest {
                agent_namespace: "guest".into(),
                agent_capabilities: vec![],
                agent_budget: unlimited_budget(),
                upload_id: upload_id(1),
                resource_type: ResourceType::ImagePng,
                expected_hash: hash,
                total_size: data.len(),
                inline_data: data,
            })
            .await
            .unwrap_err();

        assert_eq!(err, ResourceError::CapabilityDenied);
    }

    // ─── Concurrent upload limit ──────────────────────────────────────────────

    // Acceptance: 5th concurrent upload rejected (spec lines 122-124).
    #[tokio::test]
    async fn too_many_concurrent_uploads() {
        let store = default_store();
        let agent = "busy-agent";
        // Use chunked path (empty inline_data) to keep uploads in-flight.
        // The data must be large enough to not trigger inline path,
        // but we just need uploads registered, so use total_size > 0 with empty inline.
        let hash = [0xAA; 32];

        for i in 0u8..4 {
            let result = store
                .handle_upload_start(UploadStartRequest {
                    agent_namespace: agent.into(),
                    agent_capabilities: caps(),
                    agent_budget: unlimited_budget(),
                    upload_id: upload_id(i),
                    resource_type: ResourceType::ImageRgba8,
                    expected_hash: hash,
                    total_size: 128 * 1024, // 128 KiB > inline limit
                    inline_data: vec![],
                })
                .await
                .unwrap();

            // Each returns None (chunked path, no dedup hit).
            assert!(result.is_none());
        }

        // 5th upload should fail.
        let err = store
            .handle_upload_start(UploadStartRequest {
                agent_namespace: agent.into(),
                agent_capabilities: caps(),
                agent_budget: unlimited_budget(),
                upload_id: upload_id(4),
                resource_type: ResourceType::ImageRgba8,
                expected_hash: hash,
                total_size: 128 * 1024,
                inline_data: vec![],
            })
            .await
            .unwrap_err();

        assert_eq!(err, ResourceError::TooManyUploads);
        assert_eq!(err.wire_code(), "RESOURCE_TOO_MANY_UPLOADS");
    }

    // ─── Abort ────────────────────────────────────────────────────────────────

    #[tokio::test]
    async fn abort_upload_removes_inflight() {
        let store = default_store();
        let agent = "abort-agent";
        let uid = upload_id(1);
        let hash = [0xBB; 32];

        store
            .handle_upload_start(UploadStartRequest {
                agent_namespace: agent.into(),
                agent_capabilities: caps(),
                agent_budget: unlimited_budget(),
                upload_id: uid,
                resource_type: ResourceType::ImageRgba8,
                expected_hash: hash,
                total_size: 128 * 1024,
                inline_data: vec![],
            })
            .await
            .unwrap();

        assert_eq!(store.in_flight_count(agent).await, 1);
        store.abort_upload(agent, uid).await;
        assert_eq!(store.in_flight_count(agent).await, 0);
    }

    #[tokio::test]
    async fn abort_all_uploads_clears_agent() {
        let store = default_store();
        let agent = "abort-all-agent";
        let hash = [0xCC; 32];

        for i in 0u8..3 {
            store
                .handle_upload_start(UploadStartRequest {
                    agent_namespace: agent.into(),
                    agent_capabilities: caps(),
                    agent_budget: unlimited_budget(),
                    upload_id: upload_id(i),
                    resource_type: ResourceType::ImageRgba8,
                    expected_hash: hash,
                    total_size: 128 * 1024,
                    inline_data: vec![],
                })
                .await
                .unwrap();
        }

        assert_eq!(store.in_flight_count(agent).await, 3);
        store.abort_all_uploads(agent).await;
        assert_eq!(store.in_flight_count(agent).await, 0);
    }

    // ─── Out-of-order chunk rejection ─────────────────────────────────────────

    #[tokio::test]
    async fn out_of_order_chunk_rejected() {
        let store = default_store();
        let agent = "order-agent";
        let uid = upload_id(1);
        let hash = [0xDD; 32];

        store
            .handle_upload_start(UploadStartRequest {
                agent_namespace: agent.into(),
                agent_capabilities: caps(),
                agent_budget: unlimited_budget(),
                upload_id: uid,
                resource_type: ResourceType::ImageRgba8,
                expected_hash: hash,
                total_size: 256 * 1024,
                inline_data: vec![],
            })
            .await
            .unwrap();

        // Chunk index 0 is fine.
        store
            .handle_upload_chunk(agent, uid, 0, vec![0u8; 64 * 1024])
            .await
            .unwrap();

        // Chunk index 2 (skipping 1) is out of order.
        let err = store
            .handle_upload_chunk(agent, uid, 2, vec![0u8; 64 * 1024])
            .await
            .unwrap_err();

        assert!(matches!(err, ResourceError::InvalidChunk(_)));
    }

    // ─── Chunk size limit ─────────────────────────────────────────────────────

    #[tokio::test]
    async fn oversized_chunk_rejected() {
        let store = default_store();
        let agent = "chunk-size-agent";
        let uid = upload_id(1);
        let hash = [0xEE; 32];

        store
            .handle_upload_start(UploadStartRequest {
                agent_namespace: agent.into(),
                agent_capabilities: caps(),
                agent_budget: unlimited_budget(),
                upload_id: uid,
                resource_type: ResourceType::ImageRgba8,
                expected_hash: hash,
                total_size: 128 * 1024,
                inline_data: vec![],
            })
            .await
            .unwrap();

        // 64 KiB + 1 byte exceeds the chunk limit.
        let oversized = vec![0u8; CHUNK_SIZE_LIMIT + 1];
        let err = store
            .handle_upload_chunk(agent, uid, 0, oversized)
            .await
            .unwrap_err();

        assert!(matches!(err, ResourceError::InvalidChunk(_)));
    }
}
