//! Runtime-managed widget hover behavior.
//!
//! This module converts declarative `WidgetDefinition.hover_behavior` metadata
//! into concrete cursor hit-regions and delayed parameter mutations.

use std::collections::HashMap;
use std::time::{Duration, Instant};

use tze_hud_scene::graph::SceneGraph;
use tze_hud_scene::types::{DisplayEdge, GeometryPolicy, WidgetDefinition, WidgetInstance};

use crate::window::HitRegion;

/// A runtime mutation generated by hover state transitions.
#[derive(Clone, Debug, PartialEq)]
pub struct WidgetHoverMutation {
    pub instance_name: String,
    pub param_name: String,
    pub value: f32,
}

/// Runtime tracker state for one widget instance with hover behavior.
#[derive(Clone, Debug)]
pub struct WidgetHoverTracker {
    pub instance_name: String,
    pub region: HitRegion,
    pub delay: Duration,
    pub visibility_param: String,
    pub hidden_value: f32,
    pub visible_value: f32,
    pub hover_started_at: Option<Instant>,
    pub currently_visible: bool,
}

impl WidgetHoverTracker {
    fn visible_mutation(&self) -> WidgetHoverMutation {
        WidgetHoverMutation {
            instance_name: self.instance_name.clone(),
            param_name: self.visibility_param.clone(),
            value: self.visible_value,
        }
    }

    fn hidden_mutation(&self) -> WidgetHoverMutation {
        WidgetHoverMutation {
            instance_name: self.instance_name.clone(),
            param_name: self.visibility_param.clone(),
            value: self.hidden_value,
        }
    }
}

/// Build hover trackers for all widget instances that declare hover behavior.
///
/// Existing tracker timing/visibility state is preserved when the same instance
/// remains present after recomputation.
pub fn build_hover_trackers(
    scene: &SceneGraph,
    surf_w: f32,
    surf_h: f32,
    existing: &HashMap<String, WidgetHoverTracker>,
) -> HashMap<String, WidgetHoverTracker> {
    let mut trackers = HashMap::new();

    for (instance_name, instance) in &scene.widget_registry.instances {
        let Some(definition) = scene
            .widget_registry
            .definitions
            .get(&instance.widget_type_name)
        else {
            continue;
        };
        let Some(hover) = definition.hover_behavior.as_ref() else {
            continue;
        };

        let Some((x, y, w, h)) = resolve_widget_geometry(instance, definition, surf_w, surf_h)
        else {
            continue;
        };
        let Some(region) = resolve_trigger_region(x, y, w, h, hover.trigger_rect) else {
            continue;
        };

        let prev = existing.get(instance_name);
        trackers.insert(
            instance_name.clone(),
            WidgetHoverTracker {
                instance_name: instance_name.clone(),
                region,
                delay: Duration::from_millis(hover.delay_ms as u64),
                visibility_param: hover.visibility_param.clone(),
                hidden_value: hover.hidden_value,
                visible_value: hover.visible_value,
                hover_started_at: prev.and_then(|p| p.hover_started_at),
                currently_visible: prev.map(|p| p.currently_visible).unwrap_or(false),
            },
        );
    }

    trackers
}

/// Build hide mutations for trackers that disappeared between recomputations.
pub fn hidden_mutations_for_removed(
    previous: &HashMap<String, WidgetHoverTracker>,
    next: &HashMap<String, WidgetHoverTracker>,
) -> Vec<WidgetHoverMutation> {
    let mut out = Vec::new();
    for (instance_name, tracker) in previous {
        if !next.contains_key(instance_name) && tracker.currently_visible {
            out.push(tracker.hidden_mutation());
        }
    }
    out.sort_by(|a, b| {
        a.instance_name
            .cmp(&b.instance_name)
            .then(a.param_name.cmp(&b.param_name))
    });
    out
}

/// Advance hover timers and return parameter mutations to apply this frame.
pub fn tick_hover_trackers(
    trackers: &mut HashMap<String, WidgetHoverTracker>,
    cursor_x: f32,
    cursor_y: f32,
    now: Instant,
) -> Vec<WidgetHoverMutation> {
    let mut out = Vec::new();
    for tracker in trackers.values_mut() {
        let hovering = tracker.region.contains(cursor_x, cursor_y);
        if hovering {
            let started = tracker.hover_started_at.get_or_insert(now);
            if !tracker.currently_visible && now.duration_since(*started) >= tracker.delay {
                tracker.currently_visible = true;
                out.push(tracker.visible_mutation());
            }
        } else {
            tracker.hover_started_at = None;
            if tracker.currently_visible {
                tracker.currently_visible = false;
                out.push(tracker.hidden_mutation());
            }
        }
    }
    out.sort_by(|a, b| {
        a.instance_name
            .cmp(&b.instance_name)
            .then(a.param_name.cmp(&b.param_name))
    });
    out
}

/// Merge externally-supplied hit regions with widget hover hit regions.
#[allow(dead_code)]
pub fn merged_hit_regions(
    static_regions: &[HitRegion],
    trackers: &HashMap<String, WidgetHoverTracker>,
) -> Vec<HitRegion> {
    let mut out = Vec::with_capacity(static_regions.len() + trackers.len());
    out.extend_from_slice(static_regions);

    let mut names: Vec<&str> = trackers.keys().map(String::as_str).collect();
    names.sort_unstable();
    for name in names {
        if let Some(tracker) = trackers.get(name) {
            out.push(tracker.region.clone());
        }
    }
    out
}

fn resolve_widget_geometry(
    instance: &WidgetInstance,
    definition: &WidgetDefinition,
    surf_w: f32,
    surf_h: f32,
) -> Option<(f32, f32, f32, f32)> {
    let policy = instance
        .geometry_override
        .as_ref()
        .unwrap_or(&definition.default_geometry_policy);
    let (x, y, w, h) = match policy {
        GeometryPolicy::Relative {
            x_pct,
            y_pct,
            width_pct,
            height_pct,
        } => (
            surf_w * x_pct,
            surf_h * y_pct,
            surf_w * width_pct,
            surf_h * height_pct,
        ),
        GeometryPolicy::EdgeAnchored {
            edge,
            height_pct,
            width_pct,
            margin_px,
        } => {
            let w = surf_w * width_pct;
            let h = surf_h * height_pct;
            let x = (surf_w - w) / 2.0;
            let y = match edge {
                DisplayEdge::Top => *margin_px,
                DisplayEdge::Bottom => surf_h - h - margin_px,
                DisplayEdge::Left | DisplayEdge::Right => 0.0,
            };
            (x, y, w, h)
        }
    };
    if w <= 0.0 || h <= 0.0 {
        return None;
    }
    Some((x, y, w, h))
}

fn resolve_trigger_region(
    widget_x: f32,
    widget_y: f32,
    widget_w: f32,
    widget_h: f32,
    rect: tze_hud_scene::types::WidgetNormalizedRect,
) -> Option<HitRegion> {
    let x = widget_x + widget_w * rect.x_pct;
    let y = widget_y + widget_h * rect.y_pct;
    let w = widget_w * rect.width_pct;
    let h = widget_h * rect.height_pct;
    if w <= 0.0 || h <= 0.0 {
        return None;
    }
    Some(HitRegion::new(x, y, w, h))
}

#[cfg(test)]
mod tests {
    use super::*;
    use tze_hud_scene::graph::SceneGraph;
    use tze_hud_scene::types::{
        ContentionPolicy, GeometryPolicy, RenderingPolicy, WidgetDefinition, WidgetHoverBehavior,
        WidgetInstance, WidgetNormalizedRect,
    };

    fn build_test_scene() -> SceneGraph {
        let mut scene = SceneGraph::new(1920.0, 1080.0);
        let tab_id = scene.create_tab("Main", 0).expect("create tab");
        scene.widget_registry.register_definition(WidgetDefinition {
            id: "status-indicator".to_string(),
            name: "status-indicator".to_string(),
            description: "test".to_string(),
            parameter_schema: Vec::new(),
            layers: Vec::new(),
            default_geometry_policy: GeometryPolicy::Relative {
                x_pct: 0.0,
                y_pct: 0.0,
                width_pct: 1.0,
                height_pct: 1.0,
            },
            default_rendering_policy: RenderingPolicy::default(),
            default_contention_policy: ContentionPolicy::LatestWins,
            ephemeral: false,
            hover_behavior: Some(WidgetHoverBehavior {
                trigger_rect: WidgetNormalizedRect {
                    x_pct: 0.88,
                    y_pct: 0.06,
                    width_pct: 0.08,
                    height_pct: 0.22,
                },
                delay_ms: 3_000,
                visibility_param: "tooltip_visible".to_string(),
                hidden_value: 0.0,
                visible_value: 1.0,
            }),
        });
        scene.widget_registry.register_instance(WidgetInstance {
            widget_type_name: "status-indicator".to_string(),
            tab_id,
            geometry_override: Some(GeometryPolicy::Relative {
                x_pct: 1660.0 / 1920.0,
                y_pct: 8.0 / 1080.0,
                width_pct: 252.0 / 1920.0,
                height_pct: 96.0 / 1080.0,
            }),
            contention_override: None,
            instance_name: "main-status".to_string(),
            current_params: HashMap::new(),
        });
        scene
    }

    #[test]
    fn tick_hover_transitions_after_delay_and_hides_on_leave() {
        let mut trackers = HashMap::new();
        trackers.insert(
            "widget-a".to_string(),
            WidgetHoverTracker {
                instance_name: "widget-a".to_string(),
                region: HitRegion::new(10.0, 10.0, 20.0, 20.0),
                delay: Duration::from_millis(3000),
                visibility_param: "tooltip_visible".to_string(),
                hidden_value: 0.0,
                visible_value: 1.0,
                hover_started_at: None,
                currently_visible: false,
            },
        );

        let t0 = Instant::now();
        let first = tick_hover_trackers(&mut trackers, 15.0, 15.0, t0);
        assert!(first.is_empty(), "no mutation before dwell delay");

        let second =
            tick_hover_trackers(&mut trackers, 15.0, 15.0, t0 + Duration::from_millis(3001));
        assert_eq!(second.len(), 1, "must reveal after dwell threshold");
        assert_eq!(second[0].value, 1.0);

        let third = tick_hover_trackers(
            &mut trackers,
            100.0,
            100.0,
            t0 + Duration::from_millis(3010),
        );
        assert_eq!(third.len(), 1, "must hide on leave");
        assert_eq!(third[0].value, 0.0);
    }

    #[test]
    fn merged_hit_regions_appends_hover_regions_after_static_regions() {
        let static_regions = vec![HitRegion::new(1.0, 1.0, 5.0, 5.0)];
        let mut trackers = HashMap::new();
        trackers.insert(
            "b".to_string(),
            WidgetHoverTracker {
                instance_name: "b".to_string(),
                region: HitRegion::new(20.0, 20.0, 2.0, 2.0),
                delay: Duration::from_millis(1),
                visibility_param: "x".to_string(),
                hidden_value: 0.0,
                visible_value: 1.0,
                hover_started_at: None,
                currently_visible: false,
            },
        );
        let merged = merged_hit_regions(&static_regions, &trackers);
        assert_eq!(merged.len(), 2);
        assert_eq!(merged[0], static_regions[0]);
    }

    #[test]
    fn build_hover_trackers_resolves_widget_trigger_geometry() {
        let scene = build_test_scene();
        let trackers = build_hover_trackers(&scene, 1920.0, 1080.0, &HashMap::new());
        let tracker = trackers
            .get("main-status")
            .expect("main-status hover tracker must exist");

        assert!(
            tracker.region.x >= 1880.0 && tracker.region.x <= 1905.0,
            "x should resolve to top-right trigger area"
        );
        assert!(
            tracker.region.y >= 12.0 && tracker.region.y <= 18.0,
            "y should resolve near top margin"
        );
        assert!(
            tracker.region.width >= 19.0 && tracker.region.width <= 21.0,
            "width should resolve to ~20px"
        );
    }

    #[test]
    fn hidden_mutations_for_removed_emits_hide_for_visible_trackers_only() {
        let mut previous = HashMap::new();
        previous.insert(
            "widget-a".to_string(),
            WidgetHoverTracker {
                instance_name: "widget-a".to_string(),
                region: HitRegion::new(0.0, 0.0, 10.0, 10.0),
                delay: Duration::from_millis(1),
                visibility_param: "tooltip_visible".to_string(),
                hidden_value: 0.0,
                visible_value: 1.0,
                hover_started_at: None,
                currently_visible: true,
            },
        );
        previous.insert(
            "widget-b".to_string(),
            WidgetHoverTracker {
                instance_name: "widget-b".to_string(),
                region: HitRegion::new(0.0, 0.0, 10.0, 10.0),
                delay: Duration::from_millis(1),
                visibility_param: "tooltip_visible".to_string(),
                hidden_value: 0.0,
                visible_value: 1.0,
                hover_started_at: None,
                currently_visible: false,
            },
        );

        let next: HashMap<String, WidgetHoverTracker> = HashMap::new();
        let mutations = hidden_mutations_for_removed(&previous, &next);
        assert_eq!(mutations.len(), 1, "only visible tracker should emit hide");
        assert_eq!(mutations[0].instance_name, "widget-a");
        assert_eq!(mutations[0].value, 0.0);
    }
}
